DB_URL: 'jdbc:postgresql://localhost:5432/postgres'
DB_USER: 'postgres'
DB_PASSWORD: '123321'
driver: 'org.postgresql.Driver'
maps:
  - name: 'mainMenuCommands'
    key_type: 'ru.vsu.UI.Action'
    value_type: 'ru.vsu.UI.command.Command'
    entries:
      - key: 'EXIT'
        value: 'ru.vsu.UI.command.impl.ExitCommand'
      - key: 'ADD'
        value: 'ru.vsu.UI.command.impl.AddCommand'
      - key: 'EDIT'
        value: 'ru.vsu.UI.command.impl.EditCommand'
      - key: 'REMOVE'
        value: 'ru.vsu.UI.command.impl.RemoveCommand'
      - key: 'GET'
        value: 'ru.vsu.UI.command.impl.GetByIdCommand'
      - key: 'GET_ALL'
        value: 'ru.vsu.UI.command.impl.GetAllCommand'
      - key: 'GET_BY_YEAR'
        value: 'ru.vsu.UI.command.impl.GetAllByYearCommand'
      - key: 'GET_BY_MONTH'
        value: 'ru.vsu.UI.command.impl.GetAllByMonthCommand'
      - key: 'GET_BY_DATE'
        value: 'ru.vsu.UI.command.impl.GetAllByDateCommand'
      - key: 'GET_BY_NAME'
        value: 'ru.vsu.UI.command.impl.GetAllByNameCommand'
  - name: 'constructors'
    key_type: 'ru.vsu.dao.entity.EventType'
    value_type: 'ru.vsu.UI.creator.EntityCreator'
    entries:
      - key: 'BIRTHDAY'
        value: 'ru.vsu.UI.creator.impl.BirthdayConsoleCreator'
      - key: 'MEETING'
        value: 'ru.vsu.UI.creator.impl.MeetingConsoleCreator'
  - name: 'editors'
    key_type: 'ru.vsu.dao.entity.EventType'
    value_type: 'ru.vsu.UI.command.Command'
    entries:
      - key: 'BIRTHDAY'
        value: 'ru.vsu.UI.command.impl.EditBirthdayCommand'
      - key: 'MEETING'
        value: 'ru.vsu.UI.command.impl.EditMeetingCommand'
