maps:
  - name: 'mainMenuFunctions'
    key_type: 'ru.vsu.UI.Action'
    value_type: 'java.util.function.Function'
    entries:
      - key: 'EXIT'
        value: 'ru.vsu.UI.function.impl.ExitFunction'
      - key: 'ADD'
        value: 'ru.vsu.UI.function.impl.AddFunction'
      - key: 'EDIT'
        value: 'ru.vsu.UI.function.impl.EditFunction'
      - key: 'REMOVE'
        value: 'ru.vsu.UI.function.impl.RemoveFunction'
      - key: 'GET'
        value: 'ru.vsu.UI.function.impl.GetByIdFunction'
      - key: 'GET_ALL'
        value: 'ru.vsu.UI.function.impl.GetAllFunction'
      - key: 'GET_BY_YEAR'
        value: 'ru.vsu.UI.function.impl.GetAllByYearFunction'
      - key: 'GET_BY_MONTH'
        value: 'ru.vsu.UI.function.impl.GetAllByMonthFunction'
      - key: 'GET_BY_DATE'
        value: 'ru.vsu.UI.function.impl.GetAllByDateFunction'
  - name: 'findByDateFunctions'
    key_type: 'ru.vsu.service.TimeComparisonOperation'
    value_type: 'ru.vsu.service.function.TetraFunction'
    entries:
      - key: 'EQUAL'
        value: 'ru.vsu.service.function.impl.FindByDateEqualFunction'
      - key: 'BEFORE'
        value: 'ru.vsu.service.function.impl.FindByDateBeforeFunction'
      - key: 'AFTER'
        value: 'ru.vsu.service.function.impl.FindByDateAfterFunction'
  - name: 'constructors'
    key_type: 'ru.vsu.dao.entity.EventType'
    value_type: 'java.util.function.Supplier'
    entries:
      - key: 'BIRTHDAY'
        value: 'ru.vsu.UI.suppliers.impl.BirthdayCreationSupplier'
      - key: 'MEETING'
        value: 'ru.vsu.UI.suppliers.impl.MeetingCreationSupplier'
  - name: 'editors'
    key_type: 'ru.vsu.dao.entity.EventType'
    value_type: 'java.util.function.Function'
    entries:
      - key: 'BIRTHDAY'
        value: 'ru.vsu.UI.function.impl.EditBirthdayFunction'
      - key: 'MEETING'
        value: 'ru.vsu.UI.function.impl.EditMeetingFunction'
